---
title: Player Transfers 2025/26-English Premier League
output: 
  prettydoc::html_pretty:
    theme: cayman
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
source("utils.R")
source("func_data_clean.R")
source("func_subtables.R")
```

```{r data}
# Read Transfer Markt Data from the data folder ------------------------------------------------
library(here)
pl_incomings <- read.csv(here("data", "pl_incomings.csv"), check.names = TRUE)
pl_outgoings <- read.csv(here("data", "pl_outgoings.csv"), check.names = TRUE)

```

```{r}
pl_incomings<-update_cols(pl_incomings)
pl_outgoings<-update_cols(pl_outgoings)

```

```{r}
# Clean the Data sets using functions -------------------------------------

datasets <- list(pl_incomings, pl_outgoings)

datasets <- lapply(datasets, function(df) {
  if(any(colnames(df) %in% c("Left.1","In"))){
    keep_order=c("team_logo","Team","In","Age","Position","Pos","Fee","Market.value","Left.1")
    drop=c("Left","Nat.")
    player_name_col = "In"
  }
  else{
    keep_order=c("team_logo","Team","Out","Age","Position","Pos","Fee","Market.value","Joined.1")
    drop=c("Joined","Nat.")
    player_name_col = "Out"
  }
  data_clean<-clean_dataset(
    df,
    keep_order = keep_order,
    drop       = drop,
    player_name_col = player_name_col
  )
  list(
    data_clean   = data_clean,
    summary   = get_summaries(data_clean)
  )
})

```

```{r}
# Outer table logic -------------------------------------------------------

outer_table<-merge_tables(inc_data = datasets[[1]]$summary,
                          out_data=datasets[[2]]$summary,teams = teams,pl_inc_data = pl_incomings
                            )
outer_table$Expenditure<-NA
inner_table<-list(Incoming=datasets[[1]]$data_clean,
                  Outgoing=datasets[[2]]$data_clean)
inner_table<-list(Incoming=calculated_cols(inner_table$Incoming),
                  Outgoing=calculated_cols(inner_table$Outgoing))
```

```{r}
outer_table$Total_Spent_Convert.x <-parse_number(outer_table$Total_Spent_Convert.x)
outer_table$Total_Spent_Convert.y <-parse_number(outer_table$Total_Spent_Convert.y)
outer_table$Expenditure<-outer_table$Total_Spent_Convert.x-outer_table$Total_Spent_Convert.y
```

```{r table}
htmltools::browsable(
  htmltools::div(
    style = "display:grid;align-content:center;justify-content:center;width: 70%; margin: 0 auto; text-align: center;",
#    tags$div( class = "fixed-logo",
#   # Logo
#   tags$img(
#     src = here("www", "pl.svg"),  # path relative to your R project
#     height = '60px',
#     style = "margin-bottom:10px;"
#   )
# ),
    reactable(
  outer_table %>% select(team_logo,Team,Total_Spent_Convert.x,Total_Spent_Convert.y,Expenditure,-Total_Spent.x,-Total_Spent.y),
  pagination = F,
      details = function(index) {
        team <- outer_table$Team[index]
        subtables <- lapply(names(inner_table), function(dir) {
          sub <- inner_table[[dir]] %>% filter(Team == team)
          if (nrow(sub) > 0) {
            htmltools::div(
              htmltools::h2(paste(dir)),
              make_player_table(sub)
            )
          }
        })
        htmltools::div(subtables)
      },
     defaultSorted = "Expenditure",   # 👈 sort this column on load
     defaultSortOrder = "desc",        # 👈 initial order (asc / desc)
      bordered = TRUE,searchable = F,width = 800,
      height = 1100,
      striped = TRUE,
      wrap = FALSE,
      showSortIcon = FALSE,
      compact = T,outlined = T,
      highlight = TRUE,
      style = list(backgroundColor = "#fff7cc"),
      columns = list(
        team_logo = colDef(name="",
                           cell = embed_img(width=30,height=40)
        ),
        Team = colDef(name="Club",minWidth = 180,align = "center",vAlign = "center",
                      style=list(fontWeight="bold",color="black")),
        Total_Spent_Convert.x = colDef(
          name = "💸 Spent(£M)",align = "center",minWidth = 150,
          cell = data_bars(
            outer_table,
            text_position = "outside-end",   # <- completely to the right
            text_color = "black",            # ensure readable text
            bar_height = "20px",
            fill_color = "#2ECC71",
            number_fmt = scales::label_number(suffix = "M")
          )
        ),
        Total_Spent_Convert.y = colDef(minWidth = 150,
          name = "💰Sold(£M)",align = "center",
          cell = data_bars(
            outer_table,
            text_position = "outside-end",   # <- completely to the right
            text_color = "black",
            fill_color = "#E74C3C", # ensure readable text
            bar_height = "20px",
            number_fmt = scales::label_number(suffix = "M")
          )
        ),
        Expenditure=colDef(name="Net Spend",align="center",minWidth = 170,
                           style=list(fontWeight="bold",color="black"),
          cell = data_bars(outer_table,
                           align_bars ="left",
                           fill_color = c("#E74C3C","#2ECC71"),
                           text_position = "outside-end",   # <- completely to the right
                           text_color = "black",            # ensure readable text
                           bar_height = "20px",
                           number_fmt = scales::label_number(suffix = "M")  )
      )
      )
    ),
    theme = reactableTheme(
      headerStyle = list(
        whiteSpace = "nowrap",   # keep header inline
        overflow   = "visible",
        textOverflow = "clip",
        color="black",
        fontWeight="bold"
      )
    ),
    tags$p("Data source:Transfer Markt Data,Table Design:Hari Krishna")
  ))

```

```{css}

.rt-tr-details{
  background: aliceblue;
  text-align: center;
}

.rt-td-inner{
  text-align: center;
  font-family:sans-serif;
  font-size: large;
}

.main-content :first-child {
    margin-top: 0px;
    text-align:center;
    margin-left: 0px;
    padding: -2px;
}

p{
    color: #37003c;
    text-align: right;
    font-family:Monospace;
}


.page-header {
    color: black;
    text-align: center;
    background-color: bisque;
    padding: 1.5rem 2rem;
    background-image: none;
}

.rt-th {
  color:black;
}
```
